### ISSUE TITLE
作者您好，我遇到这个问题：找不到data/mlm/diag_test.conll，可是我下载的数据集没有这一个

### ISSUE THREAD

**Issue by yywhsgnd** [Zzoay/DialogDepAug#1]
Traceback (most recent call last):
  File "/home/jupyter/DD/DialogDepAug/train.py", line 164, in <module>
    run()
  File "/home/jupyter/DD/DialogDepAug/train.py", line 90, in run
    inter_dataset = InterDataset(CFG)
  File "/home/jupyter/DD/DialogDepAug/data_helper.py", line 602, in __init__
    self.inputs, self.offsets, self.heads, self.rels, self.masks, self.speakers, self.signs = self.read_data()
  File "/home/jupyter/DD/DialogDepAug/data_helper.py", line 608, in read_data
    for idx, (deps, roles, sign) in enumerate(load_inter(self.cfg.test_file)):
  File "/home/jupyter/DD/DialogDepAug/data_helper.py", line 561, in load_inter
    pred_signals = next(signal_iter)
  File "/home/jupyter/DD/DialogDepAug/data_helper.py", line 512, in load_signal
    with open(data_file, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/mlm/diag_test.conll'

**Comment by Zzoay** [comment]
你好，DialogEvalDataset应该是之前版本的dataset，我们现在已经不使用这个类了。目前使用DialogUttrInterDataset(CFG, CFG.test_file, tokenizer, test=True)来读取测试集。我们会优化一下代码以减少这样的困惑。

**Comment by yywhsgnd** [comment]
> 好，DialogEvalDataset应该是版本的数据集，我们现在已经不用这个类了。目前使用DialogUttrInterDataset(CFG, CFG.test_file, tokenizer, test=True)来读取你的测试集。我们会优化一下代码以减少这样的困惑。

好的，谢谢
